# Generated by Django 3.1.6 on 2023-08-05 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='art',
            old_name='name',
            new_name='images',
        ),
    ]
