# Generated by Django 3.1.6 on 2023-08-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20230805_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='images',
            field=models.CharField(max_length=500),
        ),
    ]
