# Generated by Django 3.1.6 on 2023-08-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20230805_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='art_id',
            field=models.IntegerField(default=0),
        ),
    ]
