# Generated by Django 3.1.6 on 2023-08-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_remove_art_art_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='images',
            field=models.ImageField(upload_to=''),
        ),
    ]
